services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obfuscation-site
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - obfuscation-network

networks:
  obfuscation-network:
    driver: bridge

